const products = [
  {
    id: 1,
    title: "Max Verstappen Helmet",
    info: "Max Verstappen 2021 1:1 Scale Helmet",
    // image: max_verstappen_helmet,
    price: "99.99",
    discountPrice: "59.99",
    rating: 4.5,
  },
  {
    id: 2,
    title: "MCLAREN HOODIE",
    info: "McLaren 2021 Team Hoodie",
    // image: mclaren_hoodie,
    price: "149.99",
    discountPrice: "69.99",
    rating: 4.5,
  },

  {
    id: 3,
    title: "REDBULL HOODIE",
    info: "REDBULL 2021 Team Hoodie",
    // image: redbull_hoodie,
    price: "149.99",
    discountPrice: "100.99",
    rating: 1.5,
  },
  {
    id: 4,
    title: "FERRARI CAP",
    info: "Scuderia Ferrari 2021 Team Cap Curved",
    // image: cap_ferrari,
    price: "49.99",
    discountPrice: "29.99",
    rating: 4.5,
  },
  {
    id: 5,
    title: "MCLAREN CAP",
    info: "MCLAREN 2021 Team Cap Curved",
    // image: cap_mclaren,
    price: "49.99",
    discountPrice: "25.99",
    rating: 3.5,
  },
  {
    id: 6,
    title: "MERCEDES CAP",
    info: "MERCEDES 2021 Team Cap Curved",
    // image: cap_mercedes,
    price: "49.99",
    discountPrice: "29.99",
    rating: 2.5,
  },
  {
    id: 7,
    title: "REDBULL CAP",
    info: "REDBULL 2021 Team Cap Curved",
    // image: cap_redbull,
    price: "49.99",
    discountPrice: "29.99",
    rating: 1.5,
  },
  {
    id: 8,
    title: "FERRARI T SHIRT",
    info: "FERRARI SAINZ 2022 Team SHIRT",
    // image: ferrari_shirt,
    price: "89.99",
    discountPrice: "49.99",
    rating: 4.5,
  },
  {
    id: 9,
    title: "MERCEDES T SHIRT",
    info: "MERCEDES 2021 Team SHIRT",
    // image: merc_shirt,
    price: "89.99",
    discountPrice: "49.99",
    rating: 3.5,
  },
  {
    id: 10,
    title: "REDBULL T SHIRT",
    info: "REDBULL 2021 Team SHIRT",
    // image: redbull_shirt,
    price: "89.99",
    discountPrice: "49.99",
    rating: 2.5,
  },
  {
    id: 11,
    title: "MERCEDES WOMENS DRESS",
    info: "MERCEDES 2021 Team DRESS",
    // image: merc_womens,
    price: "89.99",
    discountPrice: "49.99",
    rating: 1.5,
  },
  {
    id: 12,
    title: "MCLAREN WOMENS T-SHIRT",
    info: "MCLAREN 2021 Team T-SHIRT",
    // image: mclaren_womens,
    price: "89.99",
    discountPrice: "49.99",
    rating: 2.5,
  },
  {
    id: 13,
    title: "FERRARI BAG",
    info: "FERRARI 2021 Team BAG",
    // image: ferari_bag,
    price: "449.99",
    discountPrice: "249.99",
    rating: 4.5,
  },
  {
    id: 14,
    title: "MERCEDES BAG",
    info: "MERCEDES 2021 Team BAG",
    // image: merc_bag,
    price: "449.99",
    discountPrice: "249.99",
    rating: 3.5,
  },
  {
    id: 15,
    title: "REDBULL BAG",
    info: "REDBULL 2021 Team BAG",
    // image: redbull_bag,
    price: "449.99",
    discountPrice: "249.99",
    rating: 2.5,
  },
];

module.exports = products;
